package com.olp.user_mgmt.entity;
// Generated Jun 1, 2022 6:54:43 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionHistory generated by hbm2java
 */
@Entity
@Table(name = "transaction_history")
public class TransactionHistory implements java.io.Serializable {

	private Integer tranHistoryId;
	private Long customerId;
	private String catagory;
	private String action;
	private String changeLog;
	private int createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;

	public TransactionHistory() {
	}

	public TransactionHistory(String action, String changeLog, int createdBy, Date createdDate) {
		this.action = action;
		this.changeLog = changeLog;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public TransactionHistory(Long customerId, String catagory, String action, String changeLog, int createdBy,
			Date createdDate, Integer modifiedBy, Date modifiedDate) {
		this.customerId = customerId;
		this.catagory = catagory;
		this.action = action;
		this.changeLog = changeLog;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tran_history_id", unique = true, nullable = false)
	public Integer getTranHistoryId() {
		return this.tranHistoryId;
	}

	public void setTranHistoryId(Integer tranHistoryId) {
		this.tranHistoryId = tranHistoryId;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "catagory", length = 45)
	public String getCatagory() {
		return this.catagory;
	}

	public void setCatagory(String catagory) {
		this.catagory = catagory;
	}

	@Column(name = "action", nullable = false, length = 64)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "change_log", nullable = false, length = 65535)
	public String getChangeLog() {
		return this.changeLog;
	}

	public void setChangeLog(String changeLog) {
		this.changeLog = changeLog;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
